version: '3' 
services:
  db:
    image: postgres:11.1-alpine
    restart: always
    ports:
      - "5432:5432"
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    container_name: aviacommerce-dev
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    links:
      - db