version: '3' 
services:
  webapp:
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    container_name: aviacommerce-dev
    ports:
      - "4000:4000"
    depends_on:
      - db
      - elasticsearch
      - kibana
    links:
      - db
      - elasticsearch
      - kibana
  db:
    image: postgres:10
    container_name: db
    environment:
      - POSTGRES_USER=snitch_dev
      - POSTGRES_PASSWORD=snitch_dev
      - POSTGRES_DB=snitch_dev
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    ports:
      - "5601:5601"
    container_name: kibana